name: XCP-ng RPM packages build environment

on:
  push:
    branches: [ "release/hydron" ]
    tags: [ "hydron-*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          source env.sh
          TAG=${GITHUB_REF##*/}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "XCP_VERSION=${XCP_VERSION}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Build and push environment image
        shell: bash
        env:
          GCP_SA: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          ./build.sh ${XCP_VERSION} "${IMAGE_NAME}:${TAG}"
          ./push.sh "${IMAGE_NAME}:${TAG}"

      - name: Delete latest release and tag
        if: startsWith(github.ref, 'refs/heads/release/')
        run: gh release delete ${TAG} --cleanup-tag

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG }}
          tag_name: ${{ env.TAG }}
          body: |
            Whitestack XCP-ng build environment
            - For XCP-ng ${{ env.XCP_VERSION }}
          files: run.py
          draft: false
          prerelease: false
          overwrite_files: true
